#updates package.json version based on commits history 
# and commits the result (new package.json)

name: Release
on:
  workflow_run:
    workflows: ["Coverage"]
    types: [completed]
env:
  # used by semantic-release to authenticate at github and write to master
  # I used the developer tab to generate the token and then paste it to several projs
  # as a secret
  GH_TOKEN: ${{secrets.GH_TOKEN}}
  # used by semantic release to authenticate when publishing to npm
  # Generate it in NPM (you just need to be registered at npm which is simple)
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
    - name: setup semantic-release
      run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D
    - name: release
      run: npx semantic-release
